#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Nov 27, 2019 02:17:29 PM PST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #0d4f0a -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 803x582+550+136
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "1-2-3 PASS "
    vTcl:DefineAlias "$top" "Game Panel" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground #916626 -activeforeground #916626 \
        -background #6b4b1c -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text PASS 
    vTcl:DefineAlias "$top.but43" "pass_button" vTcl:WidgetProc "Game Panel" 1
    button $top.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$top.but44" "card_1" vTcl:WidgetProc "Game Panel" 1
    button $top.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$top.but45" "card_3" vTcl:WidgetProc "Game Panel" 1
    button $top.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$top.but46" "card_2" vTcl:WidgetProc "Game Panel" 1
    button $top.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black 
    vTcl:DefineAlias "$top.but47" "card_4" vTcl:WidgetProc "Game Panel" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #0d4f0a -font {-family {Kalimati} -size 15} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {PLAYER: } 
    vTcl:DefineAlias "$top.lab48" "player_name" vTcl:WidgetProc "Game Panel" 1
    button $top.but50 \
        -activebackground #f9f9f9 -activeforeground black -background #aa0000 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text QUIT 
    vTcl:DefineAlias "$top.but50" "quit_button" vTcl:WidgetProc "Game Panel" 1
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background #000000 -height 595 \
        -highlightcolor black -width 805 
    vTcl:DefineAlias "$top.fra56" "Frame1" vTcl:WidgetProc "Game Panel" 1
    set site_3_0 $top.fra56
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #000000 \
        -font {-family {Karumbi} -size 72} -foreground #ffffff \
        -highlightcolor black -text {1-2-3 Pass} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label1" vTcl:WidgetProc "Game Panel" 1
    text $site_3_0.tex58 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 246 \
        -wrap word 
    .top42.fra56.tex58 configure -font "TkTextFont"
    .top42.fra56.tex58 insert end text
    vTcl:DefineAlias "$site_3_0.tex58" "ip_textfield" vTcl:WidgetProc "Game Panel" 1
    text $site_3_0.tex59 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 246 \
        -wrap word 
    .top42.fra56.tex59 configure -font "TkTextFont"
    .top42.fra56.tex59 insert end text
    vTcl:DefineAlias "$site_3_0.tex59" "port_textfield" vTcl:WidgetProc "Game Panel" 1
    text $site_3_0.tex60 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 246 \
        -wrap word 
    .top42.fra56.tex60 configure -font "TkTextFont"
    .top42.fra56.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "player_textfield" vTcl:WidgetProc "Game Panel" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #000000 \
        -font TkDefaultFont -foreground #ffffff -highlightcolor black \
        -text {Server's IP Address: } 
    vTcl:DefineAlias "$site_3_0.lab63" "ip_label" vTcl:WidgetProc "Game Panel" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #000000 -font TkDefaultFont -foreground #ffffff \
        -highlightcolor black -text {Server's Port:} 
    vTcl:DefineAlias "$site_3_0.lab64" "port_label" vTcl:WidgetProc "Game Panel" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #000000 -font TkDefaultFont -foreground #ffffff \
        -highlightcolor black -text {Player's Name:} 
    vTcl:DefineAlias "$site_3_0.lab65" "player_label" vTcl:WidgetProc "Game Panel" 1
    button $site_3_0.but66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {START GAME} 
    vTcl:DefineAlias "$site_3_0.but66" "start_button" vTcl:WidgetProc "Game Panel" 1
    button $site_3_0.but67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {QUIT GAME} 
    vTcl:DefineAlias "$site_3_0.but67" "quit_button_menu" vTcl:WidgetProc "Game Panel" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 170 -y 40 -width 489 -relwidth 0 -height 81 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex58 \
        -in $site_3_0 -x 380 -y 190 -width 246 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex59 \
        -in $site_3_0 -x 380 -y 250 -width 246 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 380 -y 310 -width 246 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 220 -y 190 -width 149 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 210 -y 250 -width 149 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 210 -y 310 -width 149 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 320 -y 400 -width 171 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 320 -y 450 -width 171 -height 31 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 340 -y 490 -width 131 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 90 -y 220 -width 121 -relwidth 0 -height 191 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 440 -y 220 -width 121 -height 191 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 260 -y 220 -width 121 -height 191 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 610 -y 220 -width 121 -height 191 -anchor nw \
        -bordermode ignore 
    place $top.lab48 \
        -in $top -x 90 -y 40 -width 409 -relwidth 0 -height 71 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 670 -y 50 -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 0 -y 0 -width 805 -relwidth 0 -height 595 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

